name: deploy to server
on:
  push:
    branches: ["main"]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: cd public_html  && cd ${{ secrets.FOLDER_NAME }} && git pull && composer install --optimize-autoloader --no-dev && php artisan migrate
